# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PSU\Geog489-Advanced_Python\FinalProject\Geocoding\gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import os
from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt5.QtCore import QUrl

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        # Add icon located in same folder as the main py file
        icon.addPixmap(QtGui.QPixmap(os.path.dirname(__file__)+r"\worldwide-location-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.geoserviceLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.geoserviceLabel.setFont(font)
        self.geoserviceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.geoserviceLabel.setObjectName("geoserviceLabel")
        self.gridLayout_4.addWidget(self.geoserviceLabel, 2, 1, 1, 1)
        self.inputLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.gridLayout_4.addWidget(self.inputLineEdit, 0, 3, 1, 1)
        self.outputLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.gridLayout_4.addWidget(self.outputLineEdit, 1, 3, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_4.addWidget(self.outputLabel, 1, 1, 1, 1)
        self.outputSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputSaveButton.setObjectName("outputSaveButton")
        self.gridLayout_4.addWidget(self.outputSaveButton, 1, 4, 1, 1)
        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputButton.setObjectName("inputButton")
        self.gridLayout_4.addWidget(self.inputButton, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout_4.addWidget(self.inputLabel, 0, 1, 1, 1)
        self.geoserviceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.geoserviceComboBox.setObjectName("geoserviceComboBox")
        self.gridLayout_4.addWidget(self.geoserviceComboBox, 2, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.unmatchedLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.unmatchedLineEdit.setObjectName("unmatchedLineEdit")
        self.gridLayout_3.addWidget(self.unmatchedLineEdit, 9, 4, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 9, 3, 1, 1)
        self.unmatchedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.unmatchedCheckBox.setFont(font)
        self.unmatchedCheckBox.setObjectName("unmatchedCheckBox")
        self.gridLayout_3.addWidget(self.unmatchedCheckBox, 5, 4, 1, 2)
        self.geocodedSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.geocodedSaveButton.setObjectName("geocodedSaveButton")
        self.gridLayout_3.addWidget(self.geocodedSaveButton, 9, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 5, 3, 1, 1)
        self.unmatchedSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.unmatchedSaveButton.setObjectName("unmatchedSaveButton")
        self.gridLayout_3.addWidget(self.unmatchedSaveButton, 9, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 9, 7, 1, 1)
        self.geocodedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.geocodedCheckBox.setFont(font)
        self.geocodedCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.geocodedCheckBox.setObjectName("geocodedCheckBox")
        self.gridLayout_3.addWidget(self.geocodedCheckBox, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 5, 0, 1, 1)
        self.geocodedLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.geocodedLineEdit.setObjectName("geocodedLineEdit")
        self.gridLayout_3.addWidget(self.geocodedLineEdit, 9, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 9, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 5, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 18, 0, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 17, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 39, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 4, 1, 1, 1)
        self.inputColLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inputColLabel.setFont(font)
        self.inputColLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.inputColLabel.setObjectName("inputColLabel")
        self.gridLayout.addWidget(self.inputColLabel, 5, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 6, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 2, 0, 1, 1)
        self.addressLabel = QtWidgets.QLabel(self.centralwidget)
        self.addressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addressLabel.setObjectName("addressLabel")
        self.gridLayout_2.addWidget(self.addressLabel, 1, 1, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.centralwidget)
        self.cityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout_2.addWidget(self.cityLabel, 1, 2, 1, 1)
        self.zipLabel = QtWidgets.QLabel(self.centralwidget)
        self.zipLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zipLabel.setObjectName("zipLabel")
        self.gridLayout_2.addWidget(self.zipLabel, 1, 4, 1, 1)
        self.cityComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.cityComboBox.setObjectName("cityComboBox")
        self.gridLayout_2.addWidget(self.cityComboBox, 2, 2, 1, 1)
        self.stateLabel = QtWidgets.QLabel(self.centralwidget)
        self.stateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateLabel.setObjectName("stateLabel")
        self.gridLayout_2.addWidget(self.stateLabel, 1, 3, 1, 1)
        self.addressComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.addressComboBox.setObjectName("addressComboBox")
        self.gridLayout_2.addWidget(self.addressComboBox, 2, 1, 1, 1)
        self.stateComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.stateComboBox.setObjectName("stateComboBox")
        self.gridLayout_2.addWidget(self.stateComboBox, 2, 3, 1, 1)
        self.zipComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.zipComboBox.setObjectName("zipComboBox")
        self.gridLayout_2.addWidget(self.zipComboBox, 2, 4, 1, 1)
        self.uniqueComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.uniqueComboBox.setObjectName("uniqueComboBox")
        self.gridLayout_2.addWidget(self.uniqueComboBox, 2, 5, 1, 1)
        self.uniqueLabel = QtWidgets.QLabel(self.centralwidget)
        self.uniqueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.uniqueLabel.setObjectName("uniqueLabel")
        self.gridLayout_2.addWidget(self.uniqueLabel, 1, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 15, 0, 1, 3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.runButtonLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        self.runButtonLabel.setFont(font)
        self.runButtonLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.runButtonLabel.setObjectName("runButtonLabel")
        self.gridLayout_5.addWidget(self.runButtonLabel, 1, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.gridLayout_5.addWidget(self.runButton, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 40, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 40, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 40, 2, 1, 1)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webEngineView.sizePolicy().hasHeightForWidth())
        self.webEngineView.setSizePolicy(sizePolicy)
        # Load the web engine view widget with an inital US map 
        url = os.path.dirname(__file__)+r"\us_map.html"
        html_map = QUrl.fromLocalFile(url)
        self.webEngineView.load(html_map)
        self.webEngineView.setObjectName("webEngineView")
        self.gridLayout.addWidget(self.webEngineView, 41, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 42, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Geocoding tool"))
        self.geoserviceLabel.setText(_translate("MainWindow", "Select geocoder"))
        self.outputLabel.setText(_translate("MainWindow", "Output shapefile"))
        self.outputSaveButton.setText(_translate("MainWindow", "Save file"))
        self.inputButton.setText(_translate("MainWindow", "Open file"))
        self.inputLabel.setText(_translate("MainWindow", "Input Excel or CSV file"))
        self.unmatchedCheckBox.setText(_translate("MainWindow", "Export Excel or CSV of unmatched addresses"))
        self.geocodedSaveButton.setText(_translate("MainWindow", "Save file"))
        self.unmatchedSaveButton.setText(_translate("MainWindow", "Save file"))
        self.geocodedCheckBox.setText(_translate("MainWindow", "Export Excel or CSV of geocoded addresses"))
        self.inputColLabel.setText(_translate("MainWindow", "Select input fields"))
        self.addressLabel.setText(_translate("MainWindow", "Address"))
        self.cityLabel.setText(_translate("MainWindow", "City"))
        self.zipLabel.setText(_translate("MainWindow", "Zip code (optional)"))
        self.stateLabel.setText(_translate("MainWindow", "State"))
        self.uniqueLabel.setText(_translate("MainWindow", "Unique ID"))
        self.runButtonLabel.setText(_translate("MainWindow", "After running the tool, a preview of the geocoded addresses will appear in the map below."))
        self.runButton.setText(_translate("MainWindow", "Run geocoding tool"))
